### PR TITLE
Added support for all of the capture option classes to GrabzItBundle

### PR DESCRIPTION
**Pull request by GrabzIt**
I just came across your awesome component!

I thought it would be great if I could add support for all of the different option classes and then if you agree when released it will help all Symfony users. We were thinking of linking to it from our website as well giving you credit, of course, for creating such a cool Symfony bundle! If you have anything specific you want me to link to please mention it!

### CODE REVIEW

**Comment by TorbenLundsgaard** [comment]
Thanks @GrabzIt

**Comment by GrabzIt** [comment]
Awesome, we will release an article explaining how to use it soon!

**Comment by GrabzIt** [comment]
We have added your bundle here: https://grabz.it/api/php/download.aspx and here: https://grabz.it/support/index.aspx?uniqueId=php-symfony-capture-api

**Comment by TorbenLundsgaard** [comment]
Cheers @GrabzIt

**Pull request merged**
